[auth]
redirect_uri =  "http://localhost:8502/oauth2callback"
cookie_secret = "shuddha-brahma-paratpara-rama-secret-key-2026"
client_id = "58762f67-92f8-4b6c-8104-4dcd4a81d487"
client_secret = "EE08Q~tjp-b7A9TTht1rmoOBAGxbeGc6nP4Pnbnv"
server_metadata_url = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"